import React, { useState } from 'react';
import { 
  BarChart3, 
  Sparkles, 
  AlertTriangle, 
  CheckCircle2, 
  RotateCw, 
  BookOpen, 
  TrendingUp, 
  ArrowRight,
  ShieldAlert,
  Calendar
} from 'lucide-react';

export default function Dashboard({ 
  profile, 
  roadmap, 
  loading, 
  error, 
  onReplanRoadmap, 
  onStartQuiz, 
  onGoToOnboarding 
}) {
  const [replanning, setReplanning] = useState(false);
  const [replanError, setReplanError] = useState(null);

  const handleReplan = async () => {
    setReplanning(true);
    setReplanError(null);
    try {
      await onReplanRoadmap();
    } catch (err) {
      setReplanError(err.message);
    } finally {
      setReplanning(false);
    }
  };

  const skills = profile?.skills || {};
  const skillEntries = Object.entries(skills);

  // Calculate statistics
  const totalSkills = skillEntries.length;
  const avgScore = totalSkills > 0 
    ? Math.round(skillEntries.reduce((acc, [_, data]) => acc + (data.score_percent || 0), 0) / totalSkills)
    : 0;
  const reinforcementCount = skillEntries.filter(([_, data]) => data.needs_reinforcement).length;

  const getScoreColor = (percent) => {
    if (percent < 50) return {
      bar: 'bg-rose-500',
      bg: 'bg-rose-500/10',
      text: 'text-rose-400',
      border: 'border-rose-500/30'
    };
    if (percent <= 70) return {
      bar: 'bg-amber-500',
      bg: 'bg-amber-500/10',
      text: 'text-amber-400',
      border: 'border-amber-500/30'
    };
    return {
      bar: 'bg-emerald-500',
      bg: 'bg-emerald-500/10',
      text: 'text-emerald-400',
      border: 'border-emerald-500/30'
    };
  };

  return (
    <div className="space-y-8 animate-fadeIn">
      {/* Top Banner / Welcome */}
      <div className="relative overflow-hidden rounded-2xl bg-gradient-to-r from-indigo-950/80 via-slate-900 to-purple-950/80 p-6 sm:p-8 border border-indigo-500/20 shadow-2xl">
        <div className="relative z-10 flex flex-col md:flex-row md:items-center justify-between gap-6">
          <div>
            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-indigo-500/20 text-indigo-300 text-xs font-semibold mb-3 border border-indigo-500/30">
              <Sparkles className="w-3.5 h-3.5" />
              Dynamic AI-Driven Skill Engine
            </div>
            <h1 className="text-2xl sm:text-3xl font-bold tracking-tight text-white">
              Welcome back, {profile?.name || "Student"}
            </h1>
            <p className="mt-2 text-slate-400 text-sm sm:text-base max-w-2xl">
              Track mastery, address knowledge gaps with targeted assessments, and follow your dynamic 4-week roadmap generated by Claude Sonnet 4.6.
            </p>
          </div>

          {/* Quick Metrics */}
          <div className="grid grid-cols-3 gap-3 sm:gap-4 shrink-0">
            <div className="bg-slate-900/90 rounded-xl p-3 sm:p-4 border border-slate-800 text-center">
              <div className="text-2xl font-bold text-indigo-400">{avgScore}%</div>
              <div className="text-xs text-slate-400 mt-1">Avg Mastery</div>
            </div>
            <div className="bg-slate-900/90 rounded-xl p-3 sm:p-4 border border-slate-800 text-center">
              <div className={`text-2xl font-bold ${reinforcementCount > 0 ? 'text-rose-400' : 'text-emerald-400'}`}>
                {reinforcementCount}
              </div>
              <div className="text-xs text-slate-400 mt-1">Weak Areas</div>
            </div>
            <div className="bg-slate-900/90 rounded-xl p-3 sm:p-4 border border-slate-800 text-center">
              <div className="text-2xl font-bold text-purple-400">{roadmap?.weeks?.length || 4}</div>
              <div className="text-xs text-slate-400 mt-1">Weeks Planned</div>
            </div>
          </div>
        </div>
      </div>

      {/* Error alert if any */}
      {(error || replanError) && (
        <div className="p-4 rounded-xl bg-rose-500/15 border border-rose-500/30 text-rose-300 flex items-start gap-3">
          <AlertTriangle className="w-5 h-5 shrink-0 mt-0.5" />
          <div className="text-sm">
            <p className="font-semibold">Action could not be completed</p>
            <p className="mt-0.5 text-rose-200">{error || replanError}</p>
          </div>
        </div>
      )}

      {/* Main Grid: Skills Section & Roadmap Section */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
        {/* Left Column: Skill Mastery (5 cols on lg) */}
        <div className="lg:col-span-5 space-y-6">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <BarChart3 className="w-5 h-5 text-indigo-400" />
              <h2 className="text-lg font-bold text-white">Skill Mastery</h2>
            </div>
            <button
              onClick={onGoToOnboarding}
              className="text-xs text-indigo-400 hover:text-indigo-300 font-medium hover:underline flex items-center gap-1"
            >
              Edit Ratings <ArrowRight className="w-3 h-3" />
            </button>
          </div>

          {loading && totalSkills === 0 ? (
            <div className="space-y-4">
              {[1, 2, 3, 4].map((i) => (
                <div key={i} className="h-28 rounded-xl bg-slate-900/50 border border-slate-800 animate-pulse" />
              ))}
            </div>
          ) : (
            <div className="space-y-4">
              {skillEntries.map(([topic, data]) => {
                const colors = getScoreColor(data.score_percent);
                return (
                  <div
                    key={topic}
                    id={`skill-card-${topic.toLowerCase().replace(/[^a-z0-9]/g, '-')}`}
                    className={`rounded-xl p-4 bg-slate-900/80 border transition-all duration-200 ${
                      data.needs_reinforcement 
                        ? 'border-rose-500/40 bg-rose-950/10' 
                        : 'border-slate-800/80 hover:border-slate-700'
                    }`}
                  >
                    <div className="flex items-start justify-between gap-2 mb-2">
                      <div>
                        <div className="flex items-center gap-2">
                          <h3 className="font-semibold text-slate-100">{topic}</h3>
                          {data.needs_reinforcement ? (
                            <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[11px] font-semibold bg-rose-500/20 text-rose-300 border border-rose-500/30">
                              <ShieldAlert className="w-3 h-3" />
                              Needs Reinforcement
                            </span>
                          ) : (
                            <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[11px] font-medium bg-slate-800 text-slate-300">
                              {data.rating}
                            </span>
                          )}
                        </div>
                        <p className="text-xs text-slate-400 mt-0.5">
                          {data.needs_reinforcement 
                            ? 'Scored below 50% threshold. Prioritized in Week 1.' 
                            : 'Assessment status on track.'}
                        </p>
                      </div>

                      <span className={`text-lg font-bold font-mono ${colors.text}`}>
                        {data.score_percent}%
                      </span>
                    </div>

                    {/* Progress Bar */}
                    <div className="w-full bg-slate-800 rounded-full h-2.5 overflow-hidden my-3">
                      <div
                        className={`h-2.5 rounded-full transition-all duration-500 ${colors.bar}`}
                        style={{ width: `${Math.min(100, Math.max(5, data.score_percent))}%` }}
                      />
                    </div>

                    {/* Action Button */}
                    <div className="flex items-center justify-end pt-1">
                      <button
                        id={`btn-take-quiz-${topic.toLowerCase().replace(/[^a-z0-9]/g, '-')}`}
                        onClick={() => onStartQuiz(topic)}
                        className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium text-slate-200 bg-slate-800/90 hover:bg-indigo-600 hover:text-white transition-colors duration-150 border border-slate-700/60"
                      >
                        <BookOpen className="w-3.5 h-3.5" />
                        Take Assessment
                      </button>
                    </div>
                  </div>
                );
              })}
            </div>
          )}
        </div>

        {/* Right Column: AI Learning Roadmap (7 cols on lg) */}
        <div className="lg:col-span-7 space-y-6">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <Calendar className="w-5 h-5 text-purple-400" />
              <h2 className="text-lg font-bold text-white">4-Week AI Roadmap</h2>
            </div>
            
            <button
              id="btn-replan-roadmap"
              onClick={handleReplan}
              disabled={replanning}
              className="inline-flex items-center gap-2 px-3.5 py-1.5 rounded-lg text-xs font-semibold bg-indigo-600 hover:bg-indigo-500 disabled:opacity-50 text-white shadow-md shadow-indigo-600/20 transition-all duration-150"
            >
              <RotateCw className={`w-3.5 h-3.5 ${replanning ? 'animate-spin' : ''}`} />
              {replanning ? 'Replanning with Claude...' : 'Replan Roadmap'}
            </button>
          </div>

          {replanning && (
            <div className="p-4 rounded-xl bg-indigo-950/40 border border-indigo-500/30 text-indigo-200 flex items-center gap-3 animate-pulse">
              <RotateCw className="w-5 h-5 animate-spin text-indigo-400 shrink-0" />
              <div className="text-xs">
                <p className="font-semibold text-indigo-100">Planner Agent Active</p>
                <p className="text-indigo-300">Checking for subtopics needing reinforcement and generating tailored 4-week progression via Claude Sonnet 4.6...</p>
              </div>
            </div>
          )}

          {loading && !roadmap ? (
            <div className="space-y-4">
              {[1, 2, 3, 4].map((w) => (
                <div key={w} className="h-32 rounded-xl bg-slate-900/50 border border-slate-800 animate-pulse" />
              ))}
            </div>
          ) : (
            <div className="space-y-4">
              {roadmap?.weeks?.map((weekItem) => {
                const isWeek1 = weekItem.week === 1;
                const hasReinforcement = reinforcementCount > 0 && isWeek1;

                return (
                  <div
                    key={weekItem.week}
                    id={`roadmap-week-${weekItem.week}`}
                    className={`rounded-xl p-5 bg-slate-900/70 border transition-all duration-200 ${
                      hasReinforcement
                        ? 'border-indigo-500/50 bg-gradient-to-r from-indigo-950/40 to-slate-900 shadow-lg shadow-indigo-500/10'
                        : 'border-slate-800/80 hover:border-slate-700'
                    }`}
                  >
                    <div className="flex items-start justify-between gap-3 mb-2">
                      <div className="flex items-center gap-2">
                        <span className={`px-2.5 py-1 rounded-md text-xs font-bold font-mono ${
                          hasReinforcement 
                            ? 'bg-indigo-600 text-white' 
                            : 'bg-slate-800 text-slate-300'
                        }`}>
                          WEEK {weekItem.week}
                        </span>
                        {hasReinforcement ? (
                          <span className="inline-flex items-center gap-1 text-[11px] font-semibold text-indigo-300 bg-indigo-500/20 px-2 py-0.5 rounded-full border border-indigo-500/30">
                            <Sparkles className="w-3 h-3" />
                            Reinforcement Priority
                          </span>
                        ) : isWeek1 && reinforcementCount === 0 ? (
                          <span className="inline-flex items-center gap-1 text-[11px] font-semibold text-emerald-300 bg-emerald-500/20 px-2 py-0.5 rounded-full border border-emerald-500/30">
                            <CheckCircle2 className="w-3 h-3 text-emerald-400" />
                            Advanced Progression Track
                          </span>
                        ) : null}
                      </div>
                    </div>

                    {/* Topics Pill List */}
                    <div className="flex flex-wrap gap-2 my-3">
                      {weekItem.topics?.map((topicStr, idx) => (
                        <span
                          key={idx}
                          className="px-2.5 py-1 rounded-lg text-xs font-medium bg-slate-800/90 text-slate-200 border border-slate-700/50"
                        >
                          {topicStr}
                        </span>
                      ))}
                    </div>

                    {/* Pedagogical Reason */}
                    <p className="text-xs text-slate-400 italic bg-slate-950/60 p-2.5 rounded-lg border border-slate-800/50">
                      "{weekItem.reason}"
                    </p>
                  </div>
                );
              })}
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
