import React, { useState, useEffect } from 'react';
import { 
  Brain, 
  CheckCircle2, 
  XCircle, 
  AlertTriangle, 
  ArrowRight, 
  RotateCcw, 
  Compass, 
  Sparkles,
  Award,
  HelpCircle,
  ShieldAlert
} from 'lucide-react';
import { api } from '../services/api';

export default function QuizPage({ initialTopic = "SQL", onQuizComplete, onGoToDashboard }) {
  const [topic, setTopic] = useState(initialTopic);
  const [quizState, setQuizState] = useState('idle'); // 'idle' | 'loading' | 'active' | 'submitting' | 'results'
  const [quizData, setQuizData] = useState(null); // { quiz_id, questions }
  const [answers, setAnswers] = useState({}); // { [q_id]: selected_option }
  const [results, setResults] = useState(null); // { score, total, score_percent, weak_subtopics, explanations }
  const [error, setError] = useState(null);

  // If initialTopic changes from parent
  useEffect(() => {
    if (initialTopic) {
      setTopic(initialTopic);
    }
  }, [initialTopic]);

  const handleStartQuiz = async (selectedTopic = topic) => {
    setQuizState('loading');
    setError(null);
    setAnswers({});
    setResults(null);
    try {
      const data = await api.startAssessment(selectedTopic);
      setQuizData(data);
      setQuizState('active');
    } catch (err) {
      setError(err.message || 'Failed to generate assessment quiz. Please try again.');
      setQuizState('idle');
    }
  };

  const handleSelectOption = (questionId, option) => {
    setAnswers((prev) => ({
      ...prev,
      [questionId]: option,
    }));
  };

  const handleSubmitQuiz = async () => {
    // Check that all questions have an answer
    const questions = quizData?.questions || [];
    const answeredCount = Object.keys(answers).length;
    if (answeredCount < questions.length) {
      setError(`Please answer all ${questions.length} questions before submitting (currently answered ${answeredCount}/${questions.length}).`);
      return;
    }

    setQuizState('submitting');
    setError(null);
    try {
      const resultData = await api.submitAssessment(topic, quizData.quiz_id, answers);
      setResults(resultData);
      setQuizState('results');
      if (onQuizComplete) {
        onQuizComplete();
      }
    } catch (err) {
      setError(err.message || 'Failed to submit assessment answers. Please try again.');
      setQuizState('active');
    }
  };

  const availableTopics = ["SQL", "Python", "FastAPI", "HTML/CSS"];

  return (
    <div className="max-w-4xl mx-auto space-y-8 animate-fadeIn">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-slate-800 pb-6">
        <div>
          <div className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-indigo-500/10 text-indigo-400 text-xs font-semibold mb-2 border border-indigo-500/20">
            <Brain className="w-3.5 h-3.5" />
            AI Assessment Agent
          </div>
          <h1 className="text-2xl sm:text-3xl font-bold tracking-tight text-white">
            Skill Assessment
          </h1>
          <p className="text-slate-400 text-sm mt-1">
            4-question targeted multiple choice diagnostic generated by Claude Sonnet 4.6.
          </p>
        </div>

        {/* Topic Selector */}
        {quizState !== 'active' && quizState !== 'submitting' && (
          <div className="flex flex-wrap items-center gap-2">
            {availableTopics.map((t) => (
              <button
                key={t}
                id={`topic-select-${t.toLowerCase().replace(/[^a-z0-9]/g, '-')}`}
                onClick={() => {
                  setTopic(t);
                  if (quizState === 'results') setQuizState('idle');
                }}
                className={`px-3.5 py-1.5 rounded-lg text-xs font-semibold transition-all duration-150 ${
                  topic === t
                    ? 'bg-indigo-600 text-white shadow-md shadow-indigo-600/25'
                    : 'bg-slate-900 text-slate-300 hover:bg-slate-800 border border-slate-800'
                }`}
              >
                {t}
              </button>
            ))}
          </div>
        )}
      </div>

      {/* Error Banner */}
      {error && (
        <div className="p-4 rounded-xl bg-rose-500/15 border border-rose-500/30 text-rose-300 flex items-start gap-3">
          <AlertTriangle className="w-5 h-5 shrink-0 mt-0.5" />
          <div className="text-sm">
            <p className="font-semibold">Notice</p>
            <p className="mt-0.5 text-rose-200">{error}</p>
          </div>
        </div>
      )}

      {/* VIEW: Idle (Prompt to start) */}
      {quizState === 'idle' && (
        <div className="rounded-2xl bg-slate-900/60 border border-slate-800 p-8 sm:p-12 text-center space-y-6">
          <div className="w-16 h-16 rounded-2xl bg-indigo-500/10 border border-indigo-500/30 flex items-center justify-center mx-auto text-indigo-400">
            <Sparkles className="w-8 h-8" />
          </div>
          <div className="max-w-md mx-auto space-y-2">
            <h2 className="text-xl font-bold text-white">Ready to test your {topic} skills?</h2>
            <p className="text-sm text-slate-400">
              The Assessment Agent will construct 4 diagnostic questions with zero answer leaks to the client.
              Your score will immediately calibrate your personalized learning roadmap.
            </p>
          </div>
          <button
            id="btn-start-quiz"
            onClick={() => handleStartQuiz()}
            className="inline-flex items-center gap-2 px-6 py-3 rounded-xl bg-indigo-600 hover:bg-indigo-500 text-white font-semibold text-sm shadow-lg shadow-indigo-600/25 transition-all duration-150 hover:scale-105"
          >
            <Brain className="w-4 h-4" />
            Generate {topic} Assessment
          </button>
        </div>
      )}

      {/* VIEW: Loading */}
      {quizState === 'loading' && (
        <div className="rounded-2xl bg-slate-900/60 border border-slate-800 p-12 text-center space-y-4">
          <div className="w-12 h-12 rounded-full border-4 border-indigo-500/20 border-t-indigo-500 animate-spin mx-auto" />
          <h3 className="text-base font-semibold text-white">Generating Diagnostic Questions...</h3>
          <p className="text-xs text-slate-400 max-w-sm mx-auto">
            Claude Sonnet 4.6 is synthesizing 4 targeted questions for <span className="text-indigo-400 font-semibold">{topic}</span>.
          </p>
        </div>
      )}

      {/* VIEW: Active Quiz */}
      {(quizState === 'active' || quizState === 'submitting') && quizData && (
        <div className="space-y-6">
          <div className="flex items-center justify-between bg-slate-900/80 px-5 py-3 rounded-xl border border-slate-800">
            <span className="text-xs font-semibold text-slate-400">
              Topic: <strong className="text-indigo-400 font-bold">{topic}</strong>
            </span>
            <span className="text-xs font-mono text-slate-400">
              Answered: <strong className="text-white">{Object.keys(answers).length}</strong> / {quizData.questions.length}
            </span>
          </div>

          {/* Question Cards */}
          <div className="space-y-6">
            {quizData.questions.map((q, idx) => {
              const selectedAnswer = answers[q.id];
              return (
                <div 
                  key={q.id} 
                  id={`question-card-${q.id}`}
                  className="rounded-xl bg-slate-900/90 border border-slate-800 p-5 sm:p-6 space-y-4 shadow-md"
                >
                  <div className="flex items-start justify-between gap-3">
                    <span className="px-2.5 py-0.5 rounded-full text-xs font-mono font-bold bg-indigo-500/20 text-indigo-300 border border-indigo-500/30">
                      Q{idx + 1}
                    </span>
                    <span className="text-xs text-slate-400 font-medium bg-slate-800/80 px-2.5 py-0.5 rounded">
                      {q.topic_tag || topic}
                    </span>
                  </div>

                  <h3 className="text-base font-semibold text-slate-100 leading-relaxed">
                    {q.text}
                  </h3>

                  {/* Options */}
                  <div className="grid grid-cols-1 gap-2.5 pt-2">
                    {q.options.map((opt, optIdx) => {
                      const isSelected = selectedAnswer === opt;
                      return (
                        <button
                          key={optIdx}
                          id={`option-${q.id}-${optIdx}`}
                          type="button"
                          onClick={() => handleSelectOption(q.id, opt)}
                          className={`flex items-center text-left p-3.5 rounded-xl border text-sm transition-all duration-150 ${
                            isSelected
                              ? 'bg-indigo-600/20 border-indigo-500 text-white font-medium shadow-sm shadow-indigo-500/20'
                              : 'bg-slate-950/60 border-slate-800/80 text-slate-300 hover:border-slate-700 hover:bg-slate-800/40'
                          }`}
                        >
                          <span className={`w-6 h-6 rounded-lg flex items-center justify-center text-xs font-mono font-bold mr-3 shrink-0 ${
                            isSelected ? 'bg-indigo-600 text-white' : 'bg-slate-800 text-slate-400'
                          }`}>
                            {String.fromCharCode(65 + optIdx)}
                          </span>
                          <span className="flex-1">{opt}</span>
                        </button>
                      );
                    })}
                  </div>
                </div>
              );
            })}
          </div>

          {/* Submit Action */}
          <div className="flex items-center justify-end gap-3 pt-4">
            <button
              id="btn-submit-quiz"
              onClick={handleSubmitQuiz}
              disabled={quizState === 'submitting'}
              className="inline-flex items-center gap-2 px-6 py-3 rounded-xl bg-emerald-600 hover:bg-emerald-500 disabled:opacity-50 text-white font-semibold text-sm shadow-lg shadow-emerald-600/25 transition-all duration-150"
            >
              {quizState === 'submitting' ? (
                <>
                  <div className="w-4 h-4 border-2 border-white/20 border-t-white rounded-full animate-spin" />
                  Scoring Assessment Server-Side...
                </>
              ) : (
                <>
                  <CheckCircle2 className="w-4 h-4" />
                  Submit Assessment
                </>
              )}
            </button>
          </div>
        </div>
      )}

      {/* VIEW: Results Screen */}
      {quizState === 'results' && results && (
        <div className="space-y-6">
          {/* Summary Banner */}
          <div className={`rounded-2xl p-6 sm:p-8 border shadow-xl ${
            results.score_percent < 50
              ? 'bg-rose-950/20 border-rose-500/30'
              : 'bg-emerald-950/20 border-emerald-500/30'
          }`}>
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-6">
              <div className="space-y-2">
                <div className="flex items-center gap-2">
                  <Award className={`w-6 h-6 ${results.score_percent < 50 ? 'text-rose-400' : 'text-emerald-400'}`} />
                  <h2 className="text-xl font-bold text-white">Assessment Results: {topic}</h2>
                </div>
                <p className="text-sm text-slate-300">
                  {results.score_percent < 50
                    ? `Scored ${results.score} out of ${results.total} (${results.score_percent}%). Knowledge reinforcement is required.`
                    : `Well done! Scored ${results.score} out of ${results.total} (${results.score_percent}%). Mastery validated.`}
                </p>

                {results.weak_subtopics && results.weak_subtopics.length > 0 && (
                  <div className="flex items-center gap-2 pt-2">
                    <span className="text-xs font-semibold text-rose-400 flex items-center gap-1">
                      <ShieldAlert className="w-3.5 h-3.5" /> Weak subtopics:
                    </span>
                    <div className="flex flex-wrap gap-1.5">
                      {results.weak_subtopics.map((sub, i) => (
                        <span key={i} className="px-2 py-0.5 rounded text-xs font-medium bg-rose-500/20 text-rose-300 border border-rose-500/30">
                          {sub}
                        </span>
                      ))}
                    </div>
                  </div>
                )}
              </div>

              {/* Circular Score Badge */}
              <div className="flex flex-col items-center justify-center p-4 rounded-xl bg-slate-900 border border-slate-800 min-w-[120px]">
                <span className={`text-3xl font-extrabold font-mono ${
                  results.score_percent < 50 ? 'text-rose-400' : 'text-emerald-400'
                }`}>
                  {results.score_percent}%
                </span>
                <span className="text-xs text-slate-400 mt-1">{results.score} / {results.total} Correct</span>
              </div>
            </div>
          </div>

          {/* Question Review & Explanations */}
          <div className="space-y-4">
            <h3 className="text-base font-bold text-white flex items-center gap-2">
              <HelpCircle className="w-4 h-4 text-indigo-400" />
              Detailed Explanations & Server Validation
            </h3>

            {quizData?.questions?.map((q, idx) => {
              const selected = answers[q.id];
              const explanation = results.explanations?.[q.id];
              return (
                <div key={q.id} className="p-4 rounded-xl bg-slate-900/70 border border-slate-800 space-y-3">
                  <div className="flex items-start justify-between gap-2">
                    <h4 className="text-sm font-semibold text-slate-200">
                      Q{idx + 1}: {q.text}
                    </h4>
                  </div>
                  <div className="text-xs text-slate-300">
                    <span className="text-slate-500">Your Answer: </span>
                    <strong className="text-indigo-300">{selected || "No answer recorded"}</strong>
                  </div>
                  {explanation && (
                    <div className="p-3 rounded-lg bg-slate-950 text-xs text-slate-300 border border-slate-800/80">
                      <span className="font-semibold text-emerald-400">Explanation: </span>
                      {explanation}
                    </div>
                  )}
                </div>
              );
            })}
          </div>

          {/* Action buttons */}
          <div className="flex flex-wrap items-center justify-between gap-4 pt-4 border-t border-slate-800">
            <button
              onClick={() => handleStartQuiz()}
              className="inline-flex items-center gap-2 px-4 py-2.5 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-200 font-medium text-xs border border-slate-700 transition-colors"
            >
              <RotateCcw className="w-3.5 h-3.5" />
              Retake {topic} Quiz
            </button>

            <button
              id="btn-return-dashboard"
              onClick={onGoToDashboard}
              className="inline-flex items-center gap-2 px-5 py-2.5 rounded-xl bg-indigo-600 hover:bg-indigo-500 text-white font-semibold text-xs shadow-md shadow-indigo-600/25 transition-colors"
            >
              <Compass className="w-3.5 h-3.5" />
              View Updated Dashboard & Roadmap
            </button>
          </div>
        </div>
      )}
    </div>
  );
}
